name: build-docker-image

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    schedule:
        -   cron: '0 16 * * *'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    platforms: linux/amd64,linux/386,linux/arm64/v8
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: xiaozhuai/wol-forwarder:latest
            -   name: Docker Hub Description
                uses: peter-evans/dockerhub-description@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
                    repository: xiaozhuai/docker-wol-forwarder
                    short-description: ${{ github.event.repository.description }}
                    readme-filepath: ./README.md
